# K8s example - Jenkins Namespace
kind: Namespace
apiVersion: v1
metadata:
  name: jenkins-ns
  labels:
    name: jenkins-ns
---
# K8s example - Jenkins Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: agent
              containerPort: 50000
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
---
# K8s example - Jenkins Load Balancer (NLB)
apiVersion: v1
kind: Service
metadata:
  name: jenkins-nlb
  namespace: jenkins-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: agent
